name: Build macOS App

on: [push] # Запускать сборку при каждом "push" в репозиторий

jobs:
  build:
    runs-on: macos-latest # Выбираем виртуальную машину macOS
    
    steps:
    - name: Clean up and Run PyInstaller
      run: |
        rm -rf dist/ build/ # Удаляем старые папки
        pyinstaller --onefile --name "AntiSleep" mouse_mover.py
        
    - name: Checkout Code
      uses: actions/checkout@v4 # Скачиваем код из репозитория
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Устанавливаем последнюю версию Python
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyautogui pynput pyinstaller
        
    - name: Run PyInstaller
      run: |
        pyinstaller --onefile --name "AntiSleep" mouse_mover.py
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-AntiSleep-App
        path: dist/AntiSleep.app # Загружаем собранный пакет .app
        
    - name: Complete
      run: echo "Сборка завершена, .app готов к скачиванию!"
